# install docker engine. Delete firewalld.

   - name: Remove old docker-engine installation
     yum: name=docker-engine state=removed

   - name: Add EPEL repository
     yum: name=epel-release state=latest
  
   - name: Upgrade packages
     yum: name=* state=latest

   - name: Remove firewalld package
     yum: name=firewalld state=absent

   - name: Add docker repository
     yum_repository:
       name: docker
       description: Docker Repository
       baseurl: https://yum.dockerproject.org/repo/main/centos/7/
       enabled: yes
       gpgcheck: yes
       gpgkey: https://yum.dockerproject.org/gpg

   - name: Install docker-engine
     yum: name=docker-engine state=latest

   - name: Check if filedocker.service exeists
     stat: path=/usr/lib/systemd/system/docker.service
     register: docker_file_stat

   - name: Start Docker service
     command: service docker start 

   - name: Check Docker version
     shell: docker --version 
     register: docker_version
   - debug: msg="{{ docker_version.stdout }}"

